const { createYarnLock } = require('../../src/create-yarn-lock');
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

describe('create lock file', () => {
  test('create yarn lock with deep dev', () => {
    const isolateFolder = path.join(__dirname, 'test1/_isolated_');
    execSync(`rm -rf ${isolateFolder}`);
    fs.mkdirSync(isolateFolder);
    expect(
      createYarnLock({
        rootDir: path.join(__dirname, 'test1'),
        workspaceData: { pkgJson: { dependencies: { wow: '1.0.0' } } },
        projectWorkspaces: {},
        isolateFolder,
      }),
    ).toEqual(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


deep-dep@2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/deep-dep.tgz#123123"
  integrity sha512-shashashashashashashhsa==

wow@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/in-w1-dev-dep-1.tgz#123123"
  integrity sha512-shashashashashashashhsa==
  dependencies:
    deep-dep "2.0.0"
`);
  });

  test('create yarn lock with deep dev and two differnt versions', async () => {
    const isolateFolder = path.join(__dirname, 'test2/_isolated_');
    execSync(`rm -rf ${isolateFolder}`);
    fs.mkdirSync(isolateFolder);

    expect(
      createYarnLock({
        rootDir: path.join(__dirname, 'test2'),
        workspaceData: { pkgJson: { dependencies: { 'new-dep': '1.0.0', 'old-dep': '1.0.0', 'other-dep': '1.0.0' } } },
        projectWorkspaces: {},
        isolateFolder,
      }),
    ).toEqual(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


deep-dep@3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/deep-dep.tgz#123123"
  integrity sha512-shashashashashashashhsa==

deep-dep@^1.0.0, deep-dep@^1.5.0:
  version "1.5.0"
  resolved "https://registry.yarnpkg.com/deep-dep.tgz#123123"
  integrity sha512-shashashashashashashhsa==

new-dep@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/in-w1-dev-dep-1.tgz#123123"
  integrity sha512-shashashashashashashhsa==
  dependencies:
    deep-dep "^1.0.0"

old-dep@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/in-w1-dev-dep-1.tgz#123123"
  integrity sha512-shashashashashashashhsa==
  dependencies:
    deep-dep "^1.5.0"

other-dep@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/in-w1-dev-dep-1.tgz#123123"
  integrity sha512-shashashashashashashhsa==
  dependencies:
    deep-dep "3.0.0"
`);
  });
});
